spring:
  datasource:
    username: secu_user
    password: secu
    url: jdbc:mysql://localhost:3306/secu_db?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    initialization-mode: never
  jpa:
    show-sql: true
    hibernate:
      # 기존 테이블 삭제후 자동생성
      ddl-auto: create
jwt:
  issuer: jwt-app
  secretKey: jwt-practice
  tokenPrefix: Bearer

logging:
  level:
    root: INFO
    sql: DEBUG
    org.springframework:
      security: DEBUG

